import Head from 'next/head'
import Image from 'next/image'
import { collection } from 'firebase/firestore'
import { firestore } from '../firebase/clientApp'
import { useCollection } from 'react-firebase-hooks/firestore'
import { useState, useEffect, useContext } from 'react'
import { InfosAccount, AddWhitelist } from '../components'
import { MetamaskContext } from '../context'

const Home = () => {
  const {
    metaState: { accounts, chain, balance, isConnected },
    loading,
    connect,
  } = useContext(MetamaskContext)
  // const [loading, setLoading] = useState(true)
  const [success, setSuccess] = useState('')
  const [error, setError] = useState('')
  const [whitelistUsersCount, setWhitelistUserCount] = useState(0)

  const [message, disableButton] = ["Temp", false]

  const [whitelist, whitelistLoading, whitelistError] = useCollection(
    collection(firestore, 'whitelist'),
    {}
  )

  // Get the number of users in the whitelist
  useEffect(() => {
    if (whitelist) setWhitelistUserCount(whitelist.size)
  }, [whitelist])

  // Reset the success and error messages when accounts change
  useEffect(() => {
    setError('')
    setSuccess('')
  }, [accounts])

  const styles = {
    container: "flex flex-col items-center h-screen"
  }

  return (
    <div className="flex flex-col items-center justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InfosAccount {...{ isConnected, message, balance, disableButton, connect }} />
      {isConnected && (
        <AddWhitelist
          address={accounts[0]}
          registeredCount={whitelistUsersCount}
          loading={whitelistLoading}
          {...{ balance, whitelist, success, setSuccess, error, setError }}
        />
      )}
      <p>Number of users : {whitelistUsersCount}</p>
      {(success || error) && <p className={`px-4 py-2 rounded-md ${success ? 'bg-green-500' : 'bg-red-500'}`}>{success || error}</p>}
    </div>
  )
}

export default Home
