import Head from 'next/head'
import Image from 'next/image'
import { ethers } from 'ethers'
import { useState, useEffect } from 'react'
import { useMetaMask } from '../hooks/useMetaMask'

const Home = () => {
  const { accounts, message, enableButton, connect } = useMetaMask()
  const [loading, setLoading] = useState(true)
  const [balance, setBalance] = useState(0)
  const [success, setSuccess] = useState('')
  const [error, setError] = useState('')


  const styles = {
    container: "flex flex-col items-center",
    button: (disabled) => `${!disabled ? 'bg-blue-500 hover:bg-blue-700' : 'bg-gray-400'} font-bold text-white py-2 px-4 rounded`,
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button
        onClick={connect}
        disabled={!enableButton}
        className={styles.button(!enableButton)}
      >
        Connect Metamask
      </button>
      <p>{message}</p>
    </div>
  )
}

export default Home
